AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation build for /r/Futurology's Lemmy instance
Parameters:
  SSHKey:
    Description: 'The EC2 Key Pair to allow SSH access to the nodes'
    Type: 'AWS::EC2::KeyPair::KeyName'
  NumberOfAZs:
    Description: 'Number of availability zones to deploy into. Valid values are 1 and 3.'
    Default: 3
    Type: Number
    AllowedValues:
      - 1
      - 3
  StackName:
    Description: 'Name of the cloudformation stack'
    Type: String
Mappings:
  VPCMap:
    us-west-2:
      vpc: vpc-2f6ff94a
  AmiMap:
    us-west-2:
      #serverami: ami-04e914639d0cca79a # amazon linux
      #serverami: ami-0672af4b5c29cece0 # rocky 9
      serverami: ami-0dda7e535b65b6469 # rhel 9
  AZMap:
    us-west-2:
      zone1: us-west-2a
      zone2: us-west-2b
      zone3: us-west-2c
  SubnetMap:
    us-west-2:
      zone1: subnet-2f0f614a
      zone2: subnet-8f911df8
      zone3: subnet-5047e709
Resources:
  serversg:
    Type: 'AWS::EC2::SecurityGroup' 
    Properties: 
      VpcId: !FindInMap [ VPCMap, !Ref 'AWS::Region', vpc ]
      GroupDescription: Permit Any IPv4
      GroupName: cloud-server-permit-any
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: -1
      - CidrIpv6: ::0/0
        IpProtocol: -1
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: -1
      - CidrIpv6: ::0/0
        IpProtocol: -1
  server:
    Type: AWS::EC2::Instance 
    Properties:
      ImageId: !FindInMap [ AmiMap, !Ref 'AWS::Region', serverami ]
      InstanceType: t3.small
      KeyName: !Ref SSHKey
      SecurityGroupIds: [ { "Fn::GetAtt" : [ "serversg", "GroupId" ] } ]
      Tags:
      - Key: Name
        Value: !Ref StackName
      UserData: IyEvdXNyL2Jpbi9lbnYgYmFzaAoKc2V0IC14ZXVvIHBpcGVmYWlsCgpzc2hrZXlzPSJodHRwczovL2dpdGh1Yi5jb20vbG9yZHZhZHIvZnV0dXJvbG9neS1zc2gta2V5cy5naXQiCmdwZ2tleXM9Imh0dHBzOi8vZ2l0aHViLmNvbS9sb3JkdmFkci9mdXR1cm9sb2d5LWdwZy1rZXlzLmdpdCIKY29uZmlnPSJodHRwczovL2dpdGh1Yi5jb20vbG9yZHZhZHIvZnV0dXJvbG9neS1sZW1teS1zZXJ2ZXItY29uZmlnLmdpdCIKYnJhbmNoPSJtYWluIgp3b3JrZGlyPSJ3b3JrZGlyIgoKZGllKCkgewoJPiYyIGVjaG8gIkZBVEFMOiAke0A6LVVOS05PV04gRVJST1J9IgoJZXhpdCAxCn0KCmNsZWFudXAoKSB7Cglsb2NhbCBydj0iJHs/fSIKCVsgIiR7cnZ9IiA9PSAiMCIgXSB8fCB7ID4mMiBlY2hvICJGQVRBTCBGQVRBTCBGQVRBTCBGQVRBTCAhISEhISEgU0NSSVBUIERJRCBOT1QgRVhJVCBDTEVBTkxZIjsgfQp9CgpsYXN0X3NpZ25lZF9jb21taXQoKSB7Cglsb2NhbCBkaXI9MAoJWyAteiAiJHsyOi19IiBdIHx8IFsgISAtZCAiJHsyfSIgXSB8fCB7IGRpcj0xOyBwdXNoZCAiJHsyfSIgPiAvZGV2L251bGwgMj4mMSB8fCBkaWUgIkNvdWxkIG5vdCBjaGFuZ2UgZGlyZWN0b3J5IHRvIFwiJHsyfVwiLiI7IH0gCgoJWyAteiAiJHsxOi19IiBdIHx8IGdpdCBjaGVja291dCAiJHsxfSIgfHwgZGllICJDb3VsZCBub3QgY2hlY2tvdXQgYnJhbmNoIFwiJHsxfVwiLiIKCglDT01NSVQ9IiIKCglmb3IgYyBpbiAkKGdpdCBsb2cgLS1wcmV0dHk9Zm9ybWF0OiIlSCIpOyBkbwoJCWlmIGdpdCB2ZXJpZnktY29tbWl0ICIke2N9IjsgdGhlbgoJCQlDT01NSVQ9IiR7Y30iCgkJCWJyZWFrCgkJZWxzZQoJCQlDT01NSVQ9IiIKCQlmaQoJZG9uZQoKCVsgIiR7ZGlyfSIgIT0gIjEiIF0gfHwgcG9wZCA+IC9kZXYvbnVsbCAyPiYxCgoJWyAtbiAiJHtDT01NSVR9IiBdICYmIGVjaG8gIiR7Q09NTUlUfSIKfQoKdHJhcCBjbGVhbnVwIEVYSVQKCmNkIC9yb290IHx8IGRpZSAiQ291bGQgbm90IGNoYW5nZSB3b3JraW5nIGRpcmVjdG9yeSB0byAvcm9vdCIKCnN1ZG8gZG5mIC15IC0tYWxsb3dlcmFzaW5nIGluc3RhbGwgZGlybW5nciBnaXQgfHwgZGllICJDb3VsZCBub3QgaW5zdGFsbCBnaXQgYW5kIG90aGVyIHRvb2xzLiIKCmdwZyAtLWltcG9ydCA8PCBFT0YKLS0tLS1CRUdJTiBQR1AgUFVCTElDIEtFWSBCTE9DSy0tLS0tCgptRE1FWkpNWHpSWUpLd1lCQkFIYVJ3OEJBUWRBeEFrWlFGaTVNa04wWjltSXBpY0l3d1l4MElZZTdHK0IwdlNHClRXSURQaHEwSld4dmNtUjJZV1J5SUR4c2IzSmtkbUZrY2tCbWRYUjFjbTlzYjJkNUxuTnZZMmxoYkQ2SW1RUVQKRmdvQVFSWWhCQ1dqTkRIUXlHZlBhUm1lSkxIWU1sUm9ORTFmQlFKa2t4Zk5BaHNCQlFrRHdtY0FCUXNKQ0FjQwpBaUlDQmhVS0NRZ0xBZ1FXQWdNQkFoNEhBaGVBQUFvSkVMSFlNbFJvTkUxZmQxc0ErZ000T1JmemFZcTNwZGpRCkxpcWplL0NmTzFOMjNPbWZzbFZQR1VvTzVZR0VBUHNFT3IybkZGMlJBeDhvakpVNEdPN2REOHZKVTdjRGR6dUwKVHZDc21BRWFCdz09Cj1IVjl0Ci0tLS0tRU5EIFBHUCBQVUJMSUMgS0VZIEJMT0NLLS0tLS0KRU9GCgplY2hvICIyNUEzMzQzMUQwQzg2N0NGNjkxOTlFMjRCMUQ4MzI1NDY4MzQ0RDVGOjY6IiB8IGdwZyAtLWltcG9ydC1vd25lcnRydXN0CgpncGcgLS1rZXlzZXJ2ZXIga2V5cy5vcGVucGdwLm9yZyAtLXJlZnJlc2gta2V5cwoKWyAhIC1kICIke3dvcmtkaXJ9IiBdICYmIFsgISAtZSAiJHt3b3JrZGlyfSIgXSB8fCBybSAtcmYgIiR7d29ya2Rpcn0iIHx8IGRpZSAiQ291bGQgbm90IHJlbW92ZSBzdGFsZSB3b3JrZGlyIFwiJHt3b3JrZGlyfVwiLiIKCm1rZGlyIC1wICIke3dvcmtkaXJ9IiAmJiBwdXNoZCAiJHt3b3JrZGlyfSIgfHwgZGllICJDb3VsZCBub3QgY3JlYXRlIGFuZCBjZCBpbnRvIHdvcmtpbmcgZGlyZWN0b3J5IFwiJHt3b3JrZGlyfVwiLiIKCmdpdCBjbG9uZSAiJHtncGdrZXlzfSIgZ3BnLWtleXMKCm9sZGNvbW1pdD0iIgpjb21taXQ9IiQobGFzdF9zaWduZWRfY29tbWl0ICIke2JyYW5jaH0iIGdwZy1rZXlzKSIKWyAtbiAiJHtjb21taXR9IiBdIHx8IGRpZSAiTm8gbW9zdCByZWNlbnQgc2lnbmVkIGNvbW1pdCBpbiBncGcga2V5cyByZXBvLiIKd2hpbGUgWyAiJHtjb21taXR9IiAhPSAiJHtvbGRjb21taXR9IiBdOyBkbwoJcHVzaGQgZ3BnLWtleXMKCWdpdCBjaGVja291dCAiJHtjb21taXR9IgoJY2F0ICoucHViIHwgZ3BnIC0taW1wb3J0Cglwb3BkCgljb21taXQ9IiQobGFzdF9zaWduZWRfY29tbWl0ICIke2JyYW5jaH0iIGdwZy1rZXlzKSIKZG9uZQoKZ2l0IGNsb25lICIke2NvbmZpZ30iIGNvbmZpZwpjb21taXQ9IiQobGFzdF9zaWduX2NvbW1pdCAiJHticmFuY2h9IiBjb25maWcpIgpbIC1uICIke2NvbW1pdH0iIF0gfHwgZGllICJObyBtb3N0IHJlY2VudGx5IHNpZ25lZCBjb21taXQgaW4gY29uZmlnIHJlcG8uIgpwdXNoZCBjb25maWcKZ2l0IGNoZWNrb3V0ICIke2NvbW1pdH0iCgpbIC1lICJzZXR1cC5zaCIgXSB8fCBkaWUgIk5vIFwic2V0dXAuc2hcIiBzY3JpcHQgdG8gbGF1bmNoLiIKClsgLXggInNldHVwLnNoIiBdIHx8IGRpZSAiXCJzZXR1cC5zaFwiIGlzIG5vdCBleGVjdXRhYmVsLiIKCmJhc2ggLW4gInNldHVwLnNoIiB8fCBkaWUgIlwic2V0dXAuc2hcIiBkb2VzIG5vdCBwYXNzIGxpbnRpbmcgYnkgYmFzaC4iCgpleGVjIC4vc2V0dXAuc2gK
  lemmyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref server
