#!/usr/bin/env bash

set -euo pipefail

sshkeys="https://github.com/lordvadr/futurology-ssh-keys.git"
gpgkeys="https://github.com/lordvadr/futurology-gpg-keys.git"
config="https://github.com/lordvadr/futurology-lemmy-server-config.git"
branch="main"
workdir="workdir"

die() {
	>&2 echo "FATAL: ${@:-UNKNOWN ERROR}"
	exit 1
}

cleanup() {
	local rv="${?}"
	[ "${rv}" == "0" ] || { >&2 echo "FATAL FATAL FATAL FATAL !!!!!! SCRIPT DID NOT EXIT CLEANLY"; }
}

last_signed_commit() {
	pushd "${1}" || die "Could not cd into \"${1}\"."

	git checkout "${branch}" || die "Could not checkout \"${branch}\" branch."
	COMMIT=""

	for c in $(git log --pretty=format:"%H"); do
		if git verify-commit "${c}"; then
			COMMIT="${c}"
			git checkout "${c}"
			break
		else
			COMMIT=""
		fi
	done

	[ -n "${COMMIT}" ] || die "No signed commit found."

	echo "Most recent signed commit for "${1}" is \"${COMMIT}\"."
	popd
}

trap cleanup EXIT

cd /root || die "Could not change working directory to /root"

sudo dnf -y --allowerasing install dirmngr git || die "Could not install git and other tools."

gpg --import << EOF
-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEZJMXzRYJKwYBBAHaRw8BAQdAxAkZQFi5MkN0Z9mIpicIwwYx0IYe7G+B0vSG
TWIDPhq0JWxvcmR2YWRyIDxsb3JkdmFkckBmdXR1cm9sb2d5LnNvY2lhbD6ImQQT
FgoAQRYhBCWjNDHQyGfPaRmeJLHYMlRoNE1fBQJkkxfNAhsBBQkDwmcABQsJCAcC
AiICBhUKCQgLAgQWAgMBAh4HAheAAAoJELHYMlRoNE1fd1sA+gM4ORfzaYq3pdjQ
Liqje/CfO1N23OmfslVPGUoO5YGEAPsEOr2nFF2RAx8ojJU4GO7dD8vJU7cDdzuL
TvCsmAEaBw==
=HV9t
-----END PGP PUBLIC KEY BLOCK-----
EOF

echo "25A33431D0C867CF69199E24B1D8325468344D5F:6:" | gpg --import-ownertrust

gpg --keyserver keys.openpgp.org --refresh-keys

[ ! -d "${workdir}" ] && [ ! -e "${workdir}" ] || rm -rf "${workdir}" || die "Could not remove stale workdir \"${workdir}\"."

mkdir -p "${workdir}" && pushd "${workdir}" || die "Could not create and cd into working directory \"${workdir}\"."

git clone "${sshkeys}" ssh-keys
git clone "${gpgkeys}" gpg-keys
git clone "${config}" config

last_signed_commit ssh-keys
last_signed_commit gpg-keys
last_signed_commit config

pushd config
[ -e "setup.sh" ] || die "No \"setup.sh\" script to launch."

[ -x "setup.sh" ] || die "\"setup.sh\" is not executabel."

bash -n "setup.sh" || die "\"setup.sh\" does not pass linting by bash."

exec ./setup.sh
